// Generated by CoffeeScript 1.4.0
(function() {

  this.SchedulerObject = (function() {

    function SchedulerObject(time) {
      this.gameRunning = false;
      this.list = [];
      this.time = time;
    }

    SchedulerObject.prototype.setTime = function(time) {
      this.stop();
      this.time = time;
      return this.start();
    };

    SchedulerObject.prototype.start = function() {
      var f,
        _this = this;
      this.gameRunning = true;
      f = function() {
        return _this.next();
      };
      return this.interval = window.setInterval(f, this.time);
    };

    SchedulerObject.prototype.stop = function() {
      this.gameRunning = false;
      return window.clearInterval(this.interval);
    };

    SchedulerObject.prototype.add = function(sprite) {
      return this.list.push(sprite);
    };

    SchedulerObject.prototype.next = function() {
      var sprite, _i, _len, _ref, _results;
      if (this.gameRunning) {
        _ref = this.list;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          sprite = _ref[_i];
          _results.push(sprite.next());
        }
        return _results;
      }
    };

    return SchedulerObject;

  })();

}).call(this);
